from config import app, db
from flask import jsonify
from models import Major


@app.route("/")
def home():
    return "<h1>Hello</h1>"

@app.route('/major/<string:id>', methods=['GET'])
def get_major_description(id):
    major = Major.query.filter_by(id=id).first()
    if major is not None:
        return jsonify(major.to_json()), 200
    else:
        return jsonify({"error": "Major not found"}), 404
    
@app.route('/majors', methods=['GET'])
def get_majors():
    majors = Major.query.all()
    json_majors = list(map(lambda x: x.to_json(), majors))
    return jsonify({"majors": json_majors})

@app.route('/create_major/<string:major_name>/<string:major_description>', methods=['GET', 'POST'])
def create_major_entry(major_name, major_description):
    new_major = Major(
        major_name=major_name, 
        description=major_description
    )

    try: 
        db.session.add(new_major)
        db.session.commit()
    except Exception as e:
        return(f'<h1>{str(e)}</h1>')
    
    return('<h1>Done</h1>')

@app.route("/populate_majors", methods=["POST", "GET"])
def populate_majors():
    majors_to_add = [
        {"initials": "AS", "major_name": "Acturial Science","description": "In this program, you'll take courses such as the mathematics of finance, risk theory, and pension mathematics taught by professional actuaries in one of North America’s top actuarial schools. * * Waterloo Actuarial Science graduates commonly pursue careers in finance, management, education, actuary, risk analysis, and consulting. They often work at insurance companies, financial institutions, schools, and more * * Jobs that students pursue after graduation include: * * • Financial Business Analyst * • Senior Actuarial Analyst * • Advisory Analyst * • Risk Modeling Analyst"},
        {"initials": "AM", "major_name": "Applied Mathematics","description": "In Applied Mathematics, you’ll deepen your knowledge of calculus and differential equations: the foundation for most mathematical models. You’ll have lots of opportunity to put those tools to work on real-life problems — in the classroom and, if you choose co-op, during your work terms. * * Waterloo Applied Mathematics graduates commonly pursue careers in research, consulting, and development. They often work in financial institutions, universities, government, and for engineering firms. * * Jobs that students pursue after graduation include: * * • Research Assistant * • Software Engineer * • Computing Consultant"},
        {"initials": "BS", "major_name": "Biostatistics","description": "In Biostatistics, you’ll take the same core courses as Statistics students, but with the addition of specialized upper-year courses designed specifically for Biostatistics students. You'll also get the chance to get paid work experience through co-op. "},
        {"initials": "CO", "major_name": "Combinatorics and Optimization","description": "Combinatorics looks at permutations and combinations. Optimization explores ways to make any operation work more efficiently within given constraints. Together, they provide powerful methods for modelling and solving large management problems, from optimizing flight schedules to making a factory’s layout as efficient as possible. * * Waterloo Combinatorics and Optimization graduates often pursue careers in software development, data analysis, and more. They often work for entertainment companies, financial institutions, and software companies. * * Jobs that students pursue after graduation include: * * • Software Engineer * • Quantitative Analyst * • Statistical Analyst"},
        {"initials": "CM", "major_name": "Computational Mathematics","description": "In Computational Mathematics you’ll study the intersection of mathematics, statistics, optimization, and computer science, to solve problems in business, finance, medicine, science, and technology. You'll learn to analyze data sets, formulae, and images in ways that help us understand the world around us and predict and influence the future. * * Waterloo Computational Mathematics graduates often pursue careers in software development, business, and data analysis. They often work for companies in sectors such as finance, telecommunications, and more. * * Jobs that students pursue after graduation include: * * • Security Engineer * • Software Test Specialist * • Software Developer"},
        {"initials": "DS", "major_name": "Data Science","description": "Every day, huge amounts of data are generated by business, scientific, and social activity taking place all around us. With data coming from sensors, digital images, streaming video, satellite and medical imagery, and from interactions with cloud computing, data-driven approaches to decision making are being applied in areas as diverse as medicine, business, advertising, and entertainment. * * You’ll complement your core courses in statistics, mathematics, and computer science with a range of electives from many of Waterloo’s 100 subject areas. When you graduate, you’ll have the skills and knowledge to help governments and businesses make better decisions and smarter strategies. And if you take the co-op stream, you'll have up to two years of work experience on top of that."},
        {"initials": "ME", "major_name": "Mathematical Economics","description": "Over the course of your degree, you’ll become an expert at using differential calculus, differential equations, and mathematical optimization to understand economic behavior. If you choose the co-op stream, you can add paid work experience on top of that. * * Waterloo Mathematical Economics graduates commonly pursue careers in research, financial analysis, and more. They often work in financial institutions and software companies. * * Jobs that students pursue after graduation include: * * • Research Analyst * • Marketing Data Specialist * • Control Analyst"},
        {"initials": "MF", "major_name": "Mathematical Finance","description": "Offered jointly by the Department of Pure Mathematics and the Department of Statistics and Actuarial Science, Mathematical Finance is designed for students with elite mathematical abilities who wish to pursue finance combined with pure mathematics. * * Waterloo Mathematical Finance graduates often pursue careers in investment banking, financial analysis, and more. They typically work in financial institutions, investment companies, and more. * * Jobs that students pursue after graduation include: * * • Investment Analyst * * • Quantitative Portfolio Manager * • Risk Modeling Analyst"},
        {"initials": "MO", "major_name": "Mathematical Optimization","description": "You'll start with a solid foundation in math, including combinatorics, linear optimization, modelling, scheduling, forecasting, decision theory, and computer simulation. On top of that, you’ll add courses in economics, business, and management science, in addition to the ability to gain paid work experience through co-op. * * Waterloo Mathematical Optimization graduates commonly pursue careers in software development, business analysis, and operations. They often work in financial institutions, consulting companies, universities, and more. * * Jobs that students pursue after graduation include: * * • Business Analyst * • Software Developer * • Health Information Analyst"},
        {"initials": "MP", "major_name": "Mathematical Physics","description": "In Mathematical Physics, you’ll combine theoretical physics with high-level math courses in differential equations, vector calculus, and applied mathematics. You’ll also get plenty of chances to apply that learning with hands-on labs in mechanics, electricity and magnetism, computer programming, optics, and more. * * Mathematical Physics graduates commonly pursue careers in industry analysis and modelling, software development and theoretical physics research with nuclear power companies, tech companies, engineering firms, and more. Many graduates also pursue specialized master's and PhD studies. * * Jobs that students pursue after graduation include: * * • Research Assistant * • Lecturer * • Machine Learning Engineer"},
        {"initials": "PM", "major_name": "Pure Mathematics","description": "Waterloo Pure Mathematics graduates typically pursue careers in information technology, data analysis, quantitative analysis, and more. They often work for financial institutions, consulting firms, investment firms, and technology companies. * * Pure Mathematics will provide you with problem-solving skills that can be applied in industry, business, government, or graduate school. * * Jobs that students pursue after graduation include: * * • Quantitative Analyst * • Threat Intelligence Analyst * • Software Engineer"},
        {"initials": "ST", "major_name": "Statistics","description": "In today’s data-driven world, statisticians are in high demand. Get the skills you need to help businesses market new products, researchers evaluate medical treatments, governments shape effective public policy, and more. * * Waterloo Statistics graduates often pursue careers in business, market, and data analysis, investment advisory, and more. They commonly work for telecommunications companies, financial institutions, and software companies. * * Jobs that students pursue after graduation include: * * • Data Engineer * • Market Analyst * • Business Intelligence"},
    ]

    for major in majors_to_add:
        existing_major = Major.query.filter_by(major_name=major["major_name"]).first()
        if existing_major is None:
            new_major = Major(
                major_name=major["major_name"],
                description=major["description"],
                initials=major["initials"]
            )
            db.session.add(new_major)
        else:
            existing_major.description = major["description"]
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            return f'<h1>Error: {str(e)}</h1>'

    return '<h1>Done</h1>'

if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(debug=True)
    